### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by max050pl** [amitv87/remote_access#1]
There is a problem when I want to open in webbrowser localHost:8080 after node ws.js in cmd.exe
![error3](https://cloud.githubusercontent.com/assets/13357476/12075185/3b630e16-b12c-11e5-8363-09979ef948e2.png)
What should I do in this case?

**Comment by max050pl** [comment]
![error2](https://cloud.githubusercontent.com/assets/13357476/12074860/b5949526-b120-11e5-9d77-5ff2eb9ae78b.png)

**Comment by max050pl** [comment]
And this is screen from npm install command

![error4](https://cloud.githubusercontent.com/assets/13357476/12075188/b7c063b4-b12c-11e5-9b6e-ea9182469cea.png)

**Comment by amitv87** [comment]
ws.js could not find ffmpeg.exe
You need to place ffmpeg.exe in the same directory where ws.js is present
If required you can download it from here http://ffmpeg.zeranoe.com/builds/

**Comment by amitv87** [comment]
You have native code compilation issues, I am not sure about the solution.
My environment is like this
Win7 x64
VS2012 developer command-line prompt
node 0.10.28 (x64)
npm 1.4.9
I usually compile native code in administrator mode

execSync compilation problem of yours is similar to this
https://github.com/cri5ti/grunt-shell-spawn/issues/30

**Comment by max050pl** [comment]
Hey amitv87 There is now all ok ... But there is some VIDEO delay  about 5 seconds ... Audio is ok in real time but video is not synchronized...

**Comment by amitv87** [comment]
I usually get delay under 200 ms in latest chrome at screen res 1366 x 768
this ffmpeg build worked best for me
https://drive.google.com/file/d/0B59FF8y32PwNVG1mRVhmajJtUG8/view?usp=sharing

**Comment by amitv87** [comment]
Also firefox gives better video playback but lacks mse audio context for aac
